// Argentina: 32 clubes fictícios. Nomes, apelidos e mascotes em espanhol (identidade local),
// checados para não coincidir com clubes reais conhecidos. Ordem = prestígio:
// os 16 primeiros começam na Primera División, os 16 seguintes na Primera Nacional.
import type { ClubSeed } from "../types";

export const ARG_CLUBS: ClubSeed[] = [
  // Primera División
  {id: "arg-pampero", name: "Club Atlético Pampero", short: "PAM", city: "Buenos Aires", uf: "CF", colors: ["#0B3D91", "#E63946"], pattern: "h", rep: 86, cap: 57000, nickname: "El Vendaval", mascot: "Potro criollo", stadium: "Estadio El Remolino", rival: "arg-estibadores"},
  {id: "arg-estibadores", name: "Atlético Estibadores", short: "EST", city: "Buenos Aires", uf: "CF", colors: ["#6B2737", "#F2C14E"], pattern: "v", rep: 85, cap: 54000, nickname: "Los Portuarios", mascot: "Gaviota", stadium: "Estadio La Grúa", rival: "arg-pampero"},
  {id: "arg-monumento", name: "Atlético Monumento", short: "MON", city: "Rosario", uf: "SF", colors: ["#00A6A6", "#1D1D1D"], pattern: "sash", rep: 82, cap: 44000, nickname: "Los Abanderados", mascot: "Hornero", stadium: "Estadio La Barranca", rival: "arg-riberena"},
  {id: "arg-suquia", name: "Deportivo Suquía", short: "SUQ", city: "Córdoba", uf: "CBA", colors: ["#7B2CBF", "#FFFFFF"], pattern: "h", rep: 80, cap: 42000, nickname: "Los Cuarteteros", mascot: "Puma", stadium: "Estadio La Docta", rival: "arg-lacanada"},
  {id: "arg-curtidores", name: "Atlético Curtidores", short: "CUR", city: "Avellaneda", uf: "BA", colors: ["#8D5524", "#F5F5DC"], pattern: "h", rep: 78, cap: 38000, nickname: "El Curtidor", mascot: "Buey", stadium: "Estadio La Curtiembre", rival: "arg-estibadores"},
  {id: "arg-riberena", name: "Juventud Ribereña", short: "JRI", city: "Rosario", uf: "SF", colors: ["#0077B6", "#F77F00"], pattern: "half", rep: 76, cap: 34000, nickname: "El Remero", mascot: "Surubí", stadium: "Estadio Parque Ribereño", rival: "arg-monumento"},
  {id: "arg-diagonal", name: "Club Atlético Diagonal", short: "DIA", city: "La Plata", uf: "BA", colors: ["#264653", "#E9C46A"], pattern: "sash", rep: 74, cap: 30000, nickname: "El Trazado", mascot: "Búho", stadium: "Estadio La Rotonda", rival: "arg-meridiano"},
  {id: "arg-lacanada", name: "Sportivo La Cañada", short: "SLC", city: "Córdoba", uf: "CBA", colors: ["#2A9D8F", "#FFFFFF"], pattern: "v", rep: 72, cap: 28000, nickname: "Los Canaleros", mascot: "Zorro gris", stadium: "Estadio El Calicanto", rival: "arg-suquia"},
  {id: "arg-aconcagua", name: "Atlético Aconcagua", short: "ACO", city: "Mendoza", uf: "MZA", colors: ["#FFFFFF", "#6A040F"], pattern: "sash", rep: 71, cap: 32000, nickname: "Los Andinos", mascot: "Cóndor andino", stadium: "Estadio Cumbre Blanca", rival: "arg-vendimia"},
  {id: "arg-setubal", name: "Club Atlético Setúbal", short: "SET", city: "Santa Fe", uf: "SF", colors: ["#003049", "#FCBF49"], pattern: "h", rep: 69, cap: 26000, nickname: "El Laguero", mascot: "Carpincho", stadium: "Estadio Puente Colgante", rival: "arg-colastine"},
  {id: "arg-zafra", name: "Deportivo Zafra", short: "ZAF", city: "San Miguel de Tucumán", uf: "TUC", colors: ["#2D6A4F", "#FFD60A"], pattern: "v", rep: 67, cap: 25000, nickname: "Los Zafreros", mascot: "Gato montés", stadium: "Estadio El Trapiche", rival: "arg-canera"},
  {id: "arg-hilanderos", name: "Atlético Hilanderos", short: "HIL", city: "Haedo", uf: "BA", colors: ["#9D4EDD", "#F8F9FA"], pattern: "h", rep: 66, cap: 20000, nickname: "El Telar", mascot: "Araña", stadium: "Estadio La Hilandería", rival: "arg-tranviarios"},
  {id: "arg-banquina", name: "Deportivo Banquina", short: "BAN", city: "Mar del Plata", uf: "BA", colors: ["#E76F51", "#264653"], pattern: "half", rep: 64, cap: 22000, nickname: "El Pesquero", mascot: "Lobo marino", stadium: "Estadio La Escollera", rival: "arg-serrana"},
  {id: "arg-meridiano", name: "Sportivo Meridiano", short: "MER", city: "La Plata", uf: "BA", colors: ["#FFFFFF", "#2B9348"], pattern: "h", rep: 63, cap: 18000, nickname: "La Brújula", mascot: "Tero", stadium: "Estadio El Eje", rival: "arg-diagonal"},
  {id: "arg-isleno", name: "Club Atlético Isleño", short: "ISL", city: "Tigre", uf: "BA", colors: ["#0B6E4F", "#FFE66D"], pattern: "v", rep: 61, cap: 16000, nickname: "Los Canoeros", mascot: "Garza mora", stadium: "Estadio El Muelle", rival: "arg-hilanderos"},
  {id: "arg-altovalle", name: "Sportivo Alto Valle", short: "SAV", city: "Neuquén", uf: "NQN", colors: ["#D00000", "#FFFFFF"], pattern: "sash", rep: 60, cap: 15000, nickname: "El Manzanero", mascot: "Choique", stadium: "Estadio La Barda", rival: "arg-petrolera"},
  // Primera Nacional
  {id: "arg-lerma", name: "Club Atlético Lerma", short: "LER", city: "Salta", uf: "SAL", colors: ["#8B1E3F", "#F2F2F2"], pattern: "v", rep: 66, cap: 20000, nickname: "El Poncho", mascot: "Vicuña", stadium: "Estadio San Bernardo", rival: "arg-humahuaca"},
  {id: "arg-tulum", name: "Club Atlético Tulum", short: "TUL", city: "San Juan", uf: "SJ", colors: ["#F4A261", "#2A2A2A"], pattern: "h", rep: 64, cap: 19000, nickname: "El Zonda", mascot: "Guanaco", stadium: "Estadio Pie de Palo", rival: "arg-potrero"},
  {id: "arg-estuario", name: "Sportivo Estuario", short: "ESU", city: "Bahía Blanca", uf: "BA", colors: ["#023E8A", "#90E0EF"], pattern: "v", rep: 62, cap: 15000, nickname: "Los del Puerto", mascot: "Cangrejo", stadium: "Estadio La Ría", rival: "arg-banquina"},
  {id: "arg-colastine", name: "Atlético Colastiné", short: "COL", city: "Santa Fe", uf: "SF", colors: ["#FF7F11", "#FFFFFF"], pattern: "h", rep: 61, cap: 14000, nickname: "Los Doraditos", mascot: "Dorado", stadium: "Estadio Los Sauces", rival: "arg-setubal"},
  {id: "arg-humahuaca", name: "Deportivo Humahuaca", short: "HUM", city: "Humahuaca", uf: "JUJ", colors: ["#E09F3E", "#540B0E"], pattern: "sash", rep: 60, cap: 9000, nickname: "Los Quebradeños", mascot: "Llama", stadium: "Estadio Hornocal", rival: "arg-lerma"},
  {id: "arg-vendimia", name: "Atlético Vendimia", short: "VEN", city: "Luján de Cuyo", uf: "MZA", colors: ["#4A0E4E", "#C9ADA7"], pattern: "v", rep: 58, cap: 12000, nickname: "Los Viñateros", mascot: "Zorro colorado", stadium: "Estadio La Bodega", rival: "arg-aconcagua"},
  {id: "arg-chamame", name: "Deportivo Chamamé", short: "CHA", city: "Corrientes", uf: "COR", colors: ["#E9D8A6", "#AE2012"], pattern: "h", rep: 57, cap: 13000, nickname: "El Sapucay", mascot: "Yacaré", stadium: "Estadio El Acordeón", rival: "arg-yerbatero"},
  {id: "arg-yerbatero", name: "Sportivo Yerbatero", short: "YER", city: "Posadas", uf: "MIS", colors: ["#386641", "#FFFFFF"], pattern: "v", rep: 56, cap: 11000, nickname: "El Mensú", mascot: "Tucán", stadium: "Estadio Tierra Colorada", rival: "arg-chamame"},
  {id: "arg-canera", name: "Unión Cañera", short: "UCA", city: "Famaillá", uf: "TUC", colors: ["#0D3B66", "#FAF0CA"], pattern: "h", rep: 55, cap: 9000, nickname: "El Ingenio", mascot: "Quirquincho", stadium: "Estadio El Surco", rival: "arg-zafra"},
  {id: "arg-quebracho", name: "Sportivo Quebracho", short: "QUE", city: "Santiago del Estero", uf: "SDE", colors: ["#6F1D1B", "#FFE6A7"], pattern: "v", rep: 53, cap: 10000, nickname: "El Hachero", mascot: "Oso hormiguero", stadium: "Estadio El Obraje", rival: "arg-canera"},
  {id: "arg-serrana", name: "Juventud Serrana", short: "JSE", city: "Tandil", uf: "BA", colors: ["#FFFFFF", "#2B2D42"], pattern: "h", rep: 52, cap: 9000, nickname: "La Piedra", mascot: "Chimango", stadium: "Estadio El Centinela", rival: "arg-banquina"},
  {id: "arg-petrolera", name: "Juventud Petrolera", short: "JPE", city: "Comodoro Rivadavia", uf: "CHU", colors: ["#111111", "#FFB703"], pattern: "h", rep: 50, cap: 9000, nickname: "La Torre", mascot: "Pingüino", stadium: "Estadio Cerro Chenque", rival: "arg-altovalle"},
  {id: "arg-tranviarios", name: "Atlético Tranviarios", short: "TRA", city: "Buenos Aires", uf: "CF", colors: ["#CA6702", "#FFFFFF"], pattern: "sash", rep: 49, cap: 12000, nickname: "El Tranvía", mascot: "Gorrión", stadium: "Estadio La Cochera", rival: "arg-hilanderos"},
  {id: "arg-potrero", name: "Club Atlético Potrero", short: "POT", city: "San Luis", uf: "SL", colors: ["#0096C7", "#FFFFFF"], pattern: "h", rep: 48, cap: 8000, nickname: "Los Puntanos", mascot: "Mara", stadium: "Estadio La Florida", rival: "arg-tulum"},
  {id: "arg-famatina", name: "Deportivo Famatina", short: "FAM", city: "Chilecito", uf: "LR", colors: ["#9C6644", "#EDE0D4"], pattern: "v", rep: 46, cap: 6000, nickname: "El Cablecarril", mascot: "Vizcacha", stadium: "Estadio La Mejicana", rival: "arg-quebracho"},
  {id: "arg-riacho", name: "Sportivo Riacho", short: "RIA", city: "Formosa", uf: "FOR", colors: ["#3A5A40", "#F4A259"], pattern: "half", rep: 44, cap: 6000, nickname: "El Riachero", mascot: "Aguará guazú", stadium: "Estadio El Palmar", rival: "arg-chamame"},
];
