// Clubes fictícios da Inglaterra (bairros e cidades reais com combinações de nome que nenhum clube conhecido usa).
// Ordem = prestígio: os 16 primeiros começam na Premier Division, os 16 seguintes na First Division.
import type { ClubSeed } from "../types";

export const ENG_CLUBS: ClubSeed[] = [
  // Premier Division
  {id: "eng-ancoats", name: "Ancoats United", short: "ANC", city: "Manchester", uf: "MAN", colors: ["#0B3D2E", "#F2C14E"], pattern: "solid", rep: 95, cap: 76000, nickname: "The Millhands", mascot: "Abelha", stadium: "Redhill Road", rival: "eng-chorlton"},
  {id: "eng-lambeth", name: "Lambeth Athletic", short: "LAM", city: "London", uf: "LDN", colors: ["#1D3557", "#E63946"], pattern: "sash", rep: 93, cap: 62000, nickname: "The Bargemen", mascot: "Cisne", stadium: "Kennington Lane", rival: "eng-shoreditch"},
  {id: "eng-wavertree", name: "Wavertree Rovers", short: "WAV", city: "Liverpool", uf: "MSY", colors: ["#6A4C93", "#FFFFFF"], pattern: "h", rep: 91, cap: 56000, nickname: "The Dockers", mascot: "Corvo-marinho", stadium: "Dockside Park", rival: "eng-kirkdale"},
  {id: "eng-shoreditch", name: "Shoreditch Town", short: "SHO", city: "London", uf: "LDN", colors: ["#FF7F11", "#1B1B1E"], pattern: "v", rep: 89, cap: 50000, nickname: "The Weavers", mascot: "Raposa", stadium: "Curtain Road", rival: "eng-lambeth"},
  {id: "eng-byker", name: "Byker United", short: "BYK", city: "Newcastle", uf: "TWR", colors: ["#FF6B35", "#004E89"], pattern: "h", rep: 87, cap: 50000, nickname: "The Keelmen", mascot: "Gaivota", stadium: "Shields Road", rival: "eng-wearmouth"},
  {id: "eng-digbeth", name: "Digbeth Wanderers", short: "DIG", city: "Birmingham", uf: "WMD", colors: ["#9D0208", "#FFBA08"], pattern: "v", rep: 85, cap: 48000, nickname: "The Forgemen", mascot: "Touro", stadium: "Floodgate Street", rival: "eng-dudley"},
  {id: "eng-brightside", name: "Brightside Albion", short: "BRI", city: "Sheffield", uf: "SYK", colors: ["#264653", "#E9C46A"], pattern: "half", rep: 83, cap: 44000, nickname: "The Cutlers", mascot: "Peneireiro", stadium: "Attercliffe Road", rival: "eng-kirkstall"},
  {id: "eng-trentside", name: "Trentside County", short: "TRE", city: "Nottingham", uf: "NTT", colors: ["#2EC4B6", "#011627"], pattern: "sash", rep: 81, cap: 40000, nickname: "The Lacemakers", mascot: "Garça", stadium: "Embankment Park", rival: "eng-derwent"},
  {id: "eng-clifton", name: "Clifton Town", short: "CLI", city: "Bristol", uf: "BRS", colors: ["#FFD166", "#073B4C"], pattern: "h", rep: 80, cap: 38000, nickname: "The Bridgemen", mascot: "Falcão-peregrino", stadium: "Gorge Road", rival: "eng-redcliffe"},
  {id: "eng-kirkstall", name: "Kirkstall Athletic", short: "KIR", city: "Leeds", uf: "WYK", colors: ["#A01A7D", "#F6F7EB"], pattern: "v", rep: 79, cap: 37000, nickname: "The Abbeymen", mascot: "Texugo", stadium: "Abbey Fields", rival: "eng-saltaire"},
  {id: "eng-itchen", name: "Itchen Borough", short: "ITC", city: "Southampton", uf: "HAM", colors: ["#3D348B", "#F7B801"], pattern: "h", rep: 78, cap: 34000, nickname: "The Ferrymen", mascot: "Andorinha-do-mar", stadium: "Woolston Road", rival: "eng-southsea"},
  {id: "eng-etruria", name: "Etruria Rovers", short: "ETR", city: "Stoke-on-Trent", uf: "STS", colors: ["#7F5539", "#EDE0D4"], pattern: "sash", rep: 77, cap: 32000, nickname: "The Kilnmen", mascot: "Canário", stadium: "Kiln Lane", rival: "eng-derwent"},
  {id: "eng-orwell", name: "Orwell Town", short: "ORW", city: "Ipswich", uf: "SFK", colors: ["#1B998B", "#FFFFFF"], pattern: "v", rep: 76, cap: 30000, nickname: "The Harbourmen", mascot: "Cavalo", stadium: "Wherstead Road", rival: "eng-wensum"},
  {id: "eng-cleveland", name: "Cleveland County", short: "CLE", city: "Middlesbrough", uf: "CLV", colors: ["#003566", "#FFC300"], pattern: "half", rep: 74, cap: 30000, nickname: "The Ironsiders", mascot: "Garça-real", stadium: "Transporter Park", rival: "eng-wearmouth"},
  {id: "eng-pendle", name: "Pendle Athletic", short: "PEN", city: "Nelson", uf: "LAN", colors: ["#5A189A", "#E0AAFF"], pattern: "v", rep: 73, cap: 28000, nickname: "The Witches", mascot: "Gato-preto", stadium: "Pendle Road", rival: "eng-ribbleton"},
  {id: "eng-wearmouth", name: "Wearmouth Town", short: "WEA", city: "Sunderland", uf: "TWR", colors: ["#118AB2", "#FFFFFF"], pattern: "v", rep: 72, cap: 30000, nickname: "The Shipwrights", mascot: "Foca", stadium: "Pier Road", rival: "eng-byker"},
  // First Division
  {id: "eng-chorlton", name: "Chorlton Athletic", short: "CHO", city: "Manchester", uf: "MAN", colors: ["#E4572E", "#29335C"], pattern: "h", rep: 68, cap: 22000, nickname: "The Meadowmen", mascot: "Esquilo", stadium: "Meadows Lane", rival: "eng-ancoats"},
  {id: "eng-kirkdale", name: "Kirkdale Albion", short: "KDA", city: "Liverpool", uf: "MSY", colors: ["#FFFFFF", "#2B9348"], pattern: "sash", rep: 67, cap: 20000, nickname: "The Lamplighters", mascot: "Gato", stadium: "Kirkdale Park", rival: "eng-wavertree"},
  {id: "eng-southsea", name: "Southsea Rovers", short: "SOU", city: "Portsmouth", uf: "HAM", colors: ["#F28482", "#1D3557"], pattern: "h", rep: 66, cap: 19000, nickname: "The Castlemen", mascot: "Caranguejo", stadium: "Castle Field", rival: "eng-itchen"},
  {id: "eng-stepney", name: "Stepney Borough", short: "STE", city: "London", uf: "LDN", colors: ["#9A031E", "#FB8B24"], pattern: "v", rep: 65, cap: 18000, nickname: "The Sweeps", mascot: "Pardal", stadium: "Mile End Lane", rival: "eng-shoreditch"},
  {id: "eng-dudley", name: "Dudley County", short: "DUD", city: "Dudley", uf: "WMD", colors: ["#343A40", "#F8F9FA"], pattern: "solid", rep: 64, cap: 16000, nickname: "The Limestoners", mascot: "Elefante", stadium: "Castle Hill Ground", rival: "eng-digbeth"},
  {id: "eng-saltaire", name: "Saltaire Town", short: "SAL", city: "Shipley", uf: "WYK", colors: ["#6B705C", "#FFE8D6"], pattern: "sash", rep: 63, cap: 15000, nickname: "The Alpacas", mascot: "Alpaca", stadium: "Victoria Road", rival: "eng-kirkstall"},
  {id: "eng-wensum", name: "Wensum Albion", short: "WEN", city: "Norwich", uf: "NFK", colors: ["#8338EC", "#FFBE0B"], pattern: "h", rep: 62, cap: 17000, nickname: "The Riversiders", mascot: "Lontra", stadium: "Tombland Ground", rival: "eng-orwell"},
  {id: "eng-derwent", name: "Derwent Athletic", short: "DER", city: "Derby", uf: "DBY", colors: ["#2B2D42", "#EF233C"], pattern: "v", rep: 61, cap: 16000, nickname: "The Weirmen", mascot: "Cervo", stadium: "Darley Park", rival: "eng-trentside"},
  {id: "eng-cowley", name: "Cowley Rovers", short: "COW", city: "Oxford", uf: "OXF", colors: ["#90BE6D", "#277DA1"], pattern: "half", rep: 60, cap: 14000, nickname: "The Motormen", mascot: "Boi", stadium: "Works Road", rival: "eng-kennet"},
  {id: "eng-kennet", name: "Kennet United", short: "KEN", city: "Reading", uf: "BRK", colors: ["#B5179E", "#FFFFFF"], pattern: "v", rep: 58, cap: 13000, nickname: "The Lockkeepers", mascot: "Martim-pescador", stadium: "Towpath Park", rival: "eng-cowley"},
  {id: "eng-ribbleton", name: "Ribbleton Wanderers", short: "RIB", city: "Preston", uf: "LAN", colors: ["#FFFFFF", "#7209B7"], pattern: "sash", rep: 56, cap: 12000, nickname: "The Guildsmen", mascot: "Cordeiro", stadium: "Guild Road", rival: "eng-pendle"},
  {id: "eng-holderness", name: "Holderness United", short: "HOL", city: "Hull", uf: "EYK", colors: ["#F77F00", "#003049"], pattern: "h", rep: 55, cap: 12000, nickname: "The Trawlermen", mascot: "Bacalhau", stadium: "Marfleet Lane", rival: "eng-micklegate"},
  {id: "eng-tamar", name: "Tamar Wanderers", short: "TAM", city: "Plymouth", uf: "DEV", colors: ["#06D6A0", "#073B4C"], pattern: "v", rep: 53, cap: 11000, nickname: "The Tars", mascot: "Golfinho", stadium: "Devonport Lane", rival: "eng-redcliffe"},
  {id: "eng-redcliffe", name: "Redcliffe Borough", short: "RED", city: "Bristol", uf: "BRS", colors: ["#C9184A", "#FFF0F3"], pattern: "h", rep: 51, cap: 10000, nickname: "The Cranes", mascot: "Pombo", stadium: "Harbourside Ground", rival: "eng-clifton"},
  {id: "eng-solway", name: "Solway Rovers", short: "SOL", city: "Carlisle", uf: "CUM", colors: ["#1B263B", "#E0E1DD"], pattern: "half", rep: 48, cap: 9000, nickname: "The Reivers", mascot: "Ganso", stadium: "Eden Bank", rival: "eng-byker"},
  {id: "eng-micklegate", name: "Micklegate United", short: "MIC", city: "York", uf: "NYK", colors: ["#6D2E46", "#D5B9B2"], pattern: "v", rep: 44, cap: 8500, nickname: "The Snickelways", mascot: "Javali", stadium: "Bar Walls Ground", rival: "eng-holderness"},
];
