// Clubes fictícios da Espanha (nomes pesquisados para soar espanhóis sem copiar clubes reais).
// Ordem = prestígio: os 16 primeiros começam na Primera División, os 16 seguintes na Segunda División.
import type { ClubSeed } from "../types";

export const ESP_CLUBS: ClubSeed[] = [
  // Primera División
  {id: "esp-retiro", name: "Real Club Retiro", short: "RET", city: "Madrid", uf: "MAD", colors: ["#12355B", "#E0A526"], pattern: "v", rep: 94, cap: 78000, nickname: "los Leones del Retiro", mascot: "Leão", stadium: "Estadio de La Chopera", rival: "esp-castellana"},
  {id: "esp-montjuic", name: "CE Montjuïc", short: "MJC", city: "Barcelona", uf: "BCN", colors: ["#7A1F3D", "#F2C14E"], pattern: "h", rep: 92, cap: 82000, nickname: "els Muntanyencs", mascot: "Dragão", stadium: "Estadi del Mirador", rival: "esp-barceloneta"},
  {id: "esp-castellana", name: "Atlético Castellana", short: "CAS", city: "Madrid", uf: "MAD", colors: ["#D62828", "#1D3557"], pattern: "half", rep: 89, cap: 64000, nickname: "los Torreros", mascot: "Lince-ibérico", stadium: "Estadio de las Cuatro Torres", rival: "esp-retiro"},
  {id: "esp-giralda", name: "Real Giralda CF", short: "GIR", city: "Sevilla", uf: "SEV", colors: ["#3B1F5C", "#E0A800"], pattern: "v", rep: 87, cap: 58000, nickname: "los Giraldillos", mascot: "Andorinhão", stadium: "Estadio Puerta de Jerez", rival: "esp-macarena"},
  {id: "esp-albufera", name: "Real Club Albufera", short: "ALB", city: "Valencia", uf: "VLC", colors: ["#F77F00", "#FFFFFF"], pattern: "h", rep: 85, cap: 52000, nickname: "los Naranjeros", mascot: "Enguia", stadium: "Estadio de los Arrozales", rival: "esp-turia"},
  {id: "esp-artxanda", name: "Real Artxanda", short: "ART", city: "Bilbao", uf: "BIZ", colors: ["#0B6E4F", "#111111"], pattern: "v", rep: 84, cap: 50000, nickname: "los Mendizales", mascot: "Pottoka", stadium: "Estadio de Zorrotza", rival: "esp-urgull"},
  {id: "esp-marineda", name: "Racing Marineda", short: "MRN", city: "A Coruña", uf: "ACO", colors: ["#0A2342", "#7FD1E8"], pattern: "h", rep: 82, cap: 42000, nickname: "los Faroleros", mascot: "Gaivota", stadium: "Estadio de la Torre", rival: "esp-cies"},
  {id: "esp-cies", name: "Real Club Cíes", short: "CIE", city: "Vigo", uf: "PON", colors: ["#134E6F", "#F4D35E"], pattern: "sash", rep: 80, cap: 36000, nickname: "los Percebeiros", mascot: "Polvo", stadium: "Estadio do Berbés", rival: "esp-marineda"},
  {id: "esp-moncayo", name: "Deportivo Moncayo", short: "MCY", city: "Zaragoza", uf: "ZAR", colors: ["#7B2D26", "#F1FAEE"], pattern: "v", rep: 79, cap: 34000, nickname: "los Cierzos", mascot: "Quebra-ossos", stadium: "Estadio del Cierzo", rival: "esp-taconera"},
  {id: "esp-naranco", name: "Real Naranco", short: "NAR", city: "Oviedo", uf: "AST", colors: ["#1B4332", "#D8F3DC"], pattern: "h", rep: 77, cap: 30000, nickname: "los Prerrománicos", mascot: "Urso-pardo", stadium: "Estadio de Santa María", rival: "esp-cimadevilla"},
  {id: "esp-malagueta", name: "CD Malagueta", short: "MLG", city: "Málaga", uf: "MAL", colors: ["#E76F51", "#264653"], pattern: "half", rep: 76, cap: 32000, nickname: "los Biznagueros", mascot: "Camaleão", stadium: "Estadio de Gibralfaro", rival: "esp-albaicin"},
  {id: "esp-teide", name: "UD Teide", short: "TEI", city: "Santa Cruz de Tenerife", uf: "TFE", colors: ["#3A0CA3", "#FFD166"], pattern: "v", rep: 75, cap: 28000, nickname: "los Volcaneros", mascot: "Tentilhão-azul", stadium: "Estadio Las Cañadas", rival: "esp-roquenublo"},
  {id: "esp-segura", name: "Atlético Segura", short: "SEG", city: "Murcia", uf: "MUR", colors: ["#9D0208", "#FFBA08"], pattern: "h", rep: 73, cap: 26000, nickname: "los Huertanos", mascot: "Mocho", stadium: "Estadio La Huerta", rival: "esp-alcazaba"},
  {id: "esp-bellver", name: "CF Bellver", short: "BEL", city: "Palma", uf: "BAL", colors: ["#0077B6", "#FFD60A"], pattern: "sash", rep: 72, cap: 24000, nickname: "els Foners", mascot: "Abutre-preto", stadium: "Estadi des Castell", rival: "esp-montjuic"},
  {id: "esp-macarena", name: "Atlético Macarena", short: "MAC", city: "Sevilla", uf: "SEV", colors: ["#F4A261", "#003049"], pattern: "v", rep: 71, cap: 30000, nickname: "los Murallones", mascot: "Andorinha", stadium: "Estadio de la Muralla", rival: "esp-giralda"},
  {id: "esp-roquenublo", name: "CD Roque Nublo", short: "RNU", city: "Las Palmas", uf: "LPA", colors: ["#6A994E", "#F2E8CF"], pattern: "half", rep: 70, cap: 25000, nickname: "los Cumbreros", mascot: "Presa-canário", stadium: "Estadio de Tamadaba", rival: "esp-teide"},
  // Segunda División
  {id: "esp-urgull", name: "CD Urgull", short: "URG", city: "San Sebastián", uf: "GIP", colors: ["#F95738", "#0D3B66"], pattern: "h", rep: 68, cap: 22000, nickname: "los del Castillo", mascot: "Baleia-franca", stadium: "Estadio de Ulía", rival: "esp-artxanda"},
  {id: "esp-turia", name: "Deportivo Turia", short: "TUR", city: "Valencia", uf: "VLC", colors: ["#5E60CE", "#FFFFFF"], pattern: "v", rep: 67, cap: 20000, nickname: "los del Cauce", mascot: "Martim-pescador", stadium: "Campo del Cauce", rival: "esp-albufera"},
  {id: "esp-albaicin", name: "Real Albaicín", short: "ABN", city: "Granada", uf: "GRA", colors: ["#283618", "#DDA15E"], pattern: "sash", rep: 66, cap: 20000, nickname: "los Aljibes", mascot: "Cabra-montês", stadium: "Estadio de San Nicolás", rival: "esp-malagueta"},
  {id: "esp-cimadevilla", name: "Racing Cimadevilla", short: "CIM", city: "Gijón", uf: "AST", colors: ["#0081A7", "#FED9B7"], pattern: "h", rep: 65, cap: 19000, nickname: "los Balleneros", mascot: "Baleia", stadium: "Estadio del Muelle", rival: "esp-naranco"},
  {id: "esp-taconera", name: "SD Taconera", short: "TAC", city: "Pamplona", uf: "NAV", colors: ["#FFFFFF", "#E85D04"], pattern: "sash", rep: 63, cap: 17000, nickname: "los Gigantes", mascot: "Cervo", stadium: "Estadio de las Murallas", rival: "esp-moncayo"},
  {id: "esp-pisuerga", name: "Real Club Pisuerga", short: "PIS", city: "Valladolid", uf: "VLL", colors: ["#386641", "#F2CC8F"], pattern: "h", rep: 62, cap: 18000, nickname: "los Riberos", mascot: "Lontra", stadium: "Estadio de las Moreras", rival: "esp-tormes"},
  {id: "esp-tormes", name: "Atlético Tormes", short: "TOR", city: "Salamanca", uf: "SAL", colors: ["#BC6C25", "#FEFAE0"], pattern: "v", rep: 61, cap: 14000, nickname: "los de la Rana", mascot: "Rã", stadium: "Estadio del Puente Romano", rival: "esp-pisuerga"},
  {id: "esp-califato", name: "UD Califato", short: "CLF", city: "Córdoba", uf: "COR", colors: ["#6D597A", "#EAAC8B"], pattern: "half", rep: 60, cap: 16000, nickname: "los Omeyas", mascot: "Cavalo andaluz", stadium: "Estadio de la Ribera", rival: "esp-giralda"},
  {id: "esp-caleta", name: "CD Caleta", short: "CAL", city: "Cádiz", uf: "CAD", colors: ["#FFFFFF", "#EF476F"], pattern: "v", rep: 58, cap: 15000, nickname: "los Chirigoteros", mascot: "Choco", stadium: "Estadio de la Alameda", rival: "esp-odiel"},
  {id: "esp-alcazaba", name: "UD Alcazaba", short: "ALC", city: "Almería", uf: "ALM", colors: ["#F4A261", "#2A9D8F"], pattern: "sash", rep: 57, cap: 13000, nickname: "los del Cabo", mascot: "Flamingo", stadium: "Estadio Cabo de Gata", rival: "esp-segura"},
  {id: "esp-onyar", name: "CE Onyar", short: "ONY", city: "Girona", uf: "GIR", colors: ["#FFBE0B", "#3A86FF"], pattern: "h", rep: 56, cap: 12000, nickname: "els Pontaires", mascot: "Leoa", stadium: "Estadi de la Devesa", rival: "esp-montjuic"},
  {id: "esp-barceloneta", name: "Racing Barceloneta", short: "BTA", city: "Barcelona", uf: "BCN", colors: ["#023E8A", "#FFB4A2"], pattern: "v", rep: 55, cap: 11000, nickname: "els Mariners", mascot: "Caranguejo", stadium: "Camp de la Platja", rival: "esp-montjuic"},
  {id: "esp-zocodover", name: "Deportivo Zocodover", short: "ZOC", city: "Toledo", uf: "TOL", colors: ["#6A040F", "#FFD60A"], pattern: "v", rep: 53, cap: 10000, nickname: "los Espaderos", mascot: "Águia-imperial", stadium: "Estadio de la Vega Baja", rival: "esp-castellana"},
  {id: "esp-arlanzon", name: "Real Club Arlanzón", short: "ARL", city: "Burgos", uf: "BUR", colors: ["#264653", "#E9C46A"], pattern: "half", rep: 51, cap: 12000, nickname: "los Cidianos", mascot: "Cegonha", stadium: "Estadio de la Isla", rival: "esp-pisuerga"},
  {id: "esp-odiel", name: "UD Odiel", short: "ODI", city: "Huelva", uf: "HUE", colors: ["#8338EC", "#FFFFFF"], pattern: "sash", rep: 48, cap: 10000, nickname: "los Marismeños", mascot: "Colhereiro", stadium: "Estadio de las Marismas", rival: "esp-caleta"},
  {id: "esp-zadorra", name: "SD Zadorra", short: "ZAD", city: "Vitoria-Gasteiz", uf: "ALA", colors: ["#588157", "#FFFFFF"], pattern: "v", rep: 44, cap: 9000, nickname: "los Babazorros", mascot: "Milhafre", stadium: "Estadio de Salburua", rival: "esp-urgull"},
];
