// Clubes fictícios da Itália (bairros, rios e marcos reais com nomes de clube que nenhuma equipe conhecida usa).
// Ordem = prestígio: os 16 primeiros começam na Serie A, os 16 seguintes na Serie B.
import type { ClubSeed } from "../types";

export const ITA_CLUBS: ClubSeed[] = [
  // Serie A
  {id: "ita-sempione", name: "AC Sempione", short: "SEM", city: "Milano", uf: "MI", colors: ["#0B3C5D", "#D9B310"], pattern: "v", rep: 92, cap: 75000, nickname: "gli Arcieri", mascot: "Garça", stadium: "Stadio dell'Arco", rival: "ita-bicocca"},
  {id: "ita-aventino", name: "Virtus Aventino", short: "AVE", city: "Roma", uf: "RM", colors: ["#0F4C5C", "#E36414"], pattern: "half", rep: 90, cap: 70000, nickname: "gli Aranci", mascot: "Cervo", stadium: "Stadio dei Giardini", rival: "ita-gianicolo"},
  {id: "ita-lingotto", name: "Sporting Lingotto", short: "LIN", city: "Torino", uf: "TO", colors: ["#6C757D", "#FFD60A"], pattern: "sash", rep: 88, cap: 62000, nickname: "i Motoristi", mascot: "Camurça", stadium: "Stadio della Pista", rival: "ita-crocetta"},
  {id: "ita-vomero", name: "SS Vomero", short: "VOM", city: "Napoli", uf: "NA", colors: ["#1D3557", "#A8DADC"], pattern: "h", rep: 86, cap: 58000, nickname: "i Collinari", mascot: "Falcão", stadium: "Stadio Belvedere", rival: "ita-mergellina"},
  {id: "ita-lanterna", name: "AC Lanterna", short: "LAN", city: "Genova", uf: "GE", colors: ["#E63946", "#F1FAEE"], pattern: "sash", rep: 84, cap: 45000, nickname: "i Fanalisti", mascot: "Gaivota", stadium: "Stadio del Porto Antico", rival: "ita-foce"},
  {id: "ita-oltrarno", name: "AC Oltrarno", short: "OLT", city: "Firenze", uf: "FI", colors: ["#F3722C", "#1B263B"], pattern: "v", rep: 82, cap: 44000, nickname: "gli Artigiani", mascot: "Leão", stadium: "Stadio di Boboli", rival: "ita-chianti"},
  {id: "ita-bolognina", name: "US Bolognina", short: "BGN", city: "Bologna", uf: "BO", colors: ["#2A9D8F", "#E9C46A"], pattern: "h", rep: 80, cap: 40000, nickname: "i Porticati", mascot: "Galo", stadium: "Stadio della Montagnola", rival: "ita-ghirlandina"},
  {id: "ita-adige", name: "Pro Adige", short: "ADI", city: "Verona", uf: "VR", colors: ["#4A1942", "#F4D35E"], pattern: "half", rep: 79, cap: 38000, nickname: "i Romantici", mascot: "Mastim", stadium: "Stadio dell'Adige", rival: "ita-euganea"},
  {id: "ita-concadoro", name: "AC Conca d'Oro", short: "CDO", city: "Palermo", uf: "PA", colors: ["#FB5607", "#FFBE0B"], pattern: "sash", rep: 78, cap: 40000, nickname: "i Normanni", mascot: "Tartaruga", stadium: "Stadio Monte Pellegrino", rival: "ita-ognina"},
  {id: "ita-murgia", name: "AC Murgia", short: "MUR", city: "Bari", uf: "BA", colors: ["#E9D8A6", "#005F73"], pattern: "v", rep: 76, cap: 36000, nickname: "i Murgiani", mascot: "Peneireiro", stadium: "Stadio delle Gravine", rival: "ita-messapia"},
  {id: "ita-cittalta", name: "FC Città Alta", short: "CAL", city: "Bergamo", uf: "BG", colors: ["#003049", "#FCBF49"], pattern: "h", rep: 75, cap: 32000, nickname: "i Bastioni", mascot: "Cabra", stadium: "Stadio delle Mura", rival: "ita-cidneo"},
  {id: "ita-poetto", name: "Sporting Poetto", short: "POE", city: "Cagliari", uf: "CA", colors: ["#48CAE4", "#F77F00"], pattern: "half", rep: 74, cap: 26000, nickname: "i Fenicotteri", mascot: "Flamingo", stadium: "Stadio Sella del Diavolo", rival: "ita-logudoro"},
  {id: "ita-bora", name: "Bora Calcio", short: "BOR", city: "Trieste", uf: "TS", colors: ["#0A1128", "#FEFCFB"], pattern: "v", rep: 73, cap: 28000, nickname: "i Ventosi", mascot: "Cavalo lipizzano", stadium: "Stadio del Molo Audace", rival: "ita-friuli"},
  {id: "ita-oltretorrente", name: "US Oltretorrente", short: "OTR", city: "Parma", uf: "PR", colors: ["#6A040F", "#FFFFFF"], pattern: "sash", rep: 71, cap: 25000, nickname: "i Borghigiani", mascot: "Gato", stadium: "Stadio del Torrente", rival: "ita-ghirlandina"},
  {id: "ita-rialto", name: "AC Rialto", short: "RIA", city: "Venezia", uf: "VE", colors: ["#1D4E89", "#F2A541"], pattern: "h", rep: 70, cap: 24000, nickname: "i Gondolieri", mascot: "Pombo", stadium: "Stadio della Laguna", rival: "ita-euganea"},
  {id: "ita-lario", name: "AC Lario", short: "LAR", city: "Como", uf: "CO", colors: ["#386641", "#F2E8CF"], pattern: "v", rep: 68, cap: 22000, nickname: "i Barcaioli", mascot: "Mergulhão", stadium: "Stadio della Riva", rival: "ita-sempione"},
  // Serie B
  {id: "ita-bicocca", name: "AC Bicocca", short: "BIC", city: "Milano", uf: "MI", colors: ["#264653", "#E76F51"], pattern: "h", rep: 66, cap: 20000, nickname: "gli Operai", mascot: "Lebre", stadium: "Stadio della Fabbrica", rival: "ita-sempione"},
  {id: "ita-gianicolo", name: "US Gianicolo", short: "GIA", city: "Roma", uf: "RM", colors: ["#FFFFFF", "#6A994E"], pattern: "sash", rep: 65, cap: 18000, nickname: "i Cannonieri", mascot: "Estorninho", stadium: "Stadio del Fontanone", rival: "ita-aventino"},
  {id: "ita-crocetta", name: "Pro Crocetta", short: "CRO", city: "Torino", uf: "TO", colors: ["#5F0F40", "#FB8B24"], pattern: "v", rep: 64, cap: 16000, nickname: "i Borghesi", mascot: "Gato-montês", stadium: "Stadio del Mercato", rival: "ita-lingotto"},
  {id: "ita-mergellina", name: "US Mergellina", short: "MER", city: "Napoli", uf: "NA", colors: ["#F94144", "#F9C74F"], pattern: "h", rep: 63, cap: 17000, nickname: "i Pescatori", mascot: "Polvo", stadium: "Stadio del Molosiglio", rival: "ita-vomero"},
  {id: "ita-foce", name: "US Foce", short: "FOC", city: "Genova", uf: "GE", colors: ["#577590", "#F9844A"], pattern: "half", rep: 62, cap: 15000, nickname: "i Marinai", mascot: "Caranguejo", stadium: "Stadio della Fiera", rival: "ita-lanterna"},
  {id: "ita-euganea", name: "Virtus Euganea", short: "EUG", city: "Padova", uf: "PD", colors: ["#43AA8B", "#FFFFFF"], pattern: "v", rep: 61, cap: 16000, nickname: "i Termali", mascot: "Cabra-montês", stadium: "Stadio dei Colli", rival: "ita-adige"},
  {id: "ita-ognina", name: "Sporting Ognina", short: "OGN", city: "Catania", uf: "CT", colors: ["#111111", "#F8961E"], pattern: "sash", rep: 60, cap: 18000, nickname: "i Lavici", mascot: "Ouriço-do-mar", stadium: "Stadio della Scogliera", rival: "ita-concadoro"},
  {id: "ita-ghirlandina", name: "AC Ghirlandina", short: "GHI", city: "Modena", uf: "MO", colors: ["#3A5A40", "#FFD166"], pattern: "h", rep: 59, cap: 15000, nickname: "i Campanari", mascot: "Rã", stadium: "Stadio della Secchia", rival: "ita-bolognina"},
  {id: "ita-messapia", name: "AC Messapia", short: "MES", city: "Lecce", uf: "LE", colors: ["#9E2A2B", "#FFF3B0"], pattern: "v", rep: 57, cap: 14000, nickname: "i Barocchi", mascot: "Lagarto", stadium: "Stadio della Pietra", rival: "ita-murgia"},
  {id: "ita-cidneo", name: "AC Cidneo", short: "CID", city: "Brescia", uf: "BS", colors: ["#335C67", "#FFF3B0"], pattern: "half", rep: 56, cap: 13000, nickname: "i Castellani", mascot: "Pardal", stadium: "Stadio del Castello", rival: "ita-cittalta"},
  {id: "ita-logudoro", name: "AC Logudoro", short: "LOG", city: "Sassari", uf: "SS", colors: ["#BC4749", "#F2E8CF"], pattern: "sash", rep: 55, cap: 12000, nickname: "i Pastori", mascot: "Muflão", stadium: "Stadio dei Nuraghi", rival: "ita-poetto"},
  {id: "ita-friuli", name: "US Friuli", short: "FRI", city: "Udine", uf: "UD", colors: ["#1B263B", "#FFC300"], pattern: "h", rep: 53, cap: 12000, nickname: "i Furlani", mascot: "Cegonha", stadium: "Stadio del Tagliamento", rival: "ita-bora"},
  {id: "ita-chianti", name: "Pro Chianti", short: "CHI", city: "Siena", uf: "SI", colors: ["#6D1A36", "#F1FAEE"], pattern: "v", rep: 51, cap: 11000, nickname: "i Vignaioli", mascot: "Javali", stadium: "Stadio delle Colline", rival: "ita-oltrarno"},
  {id: "ita-trasimeno", name: "US Trasimeno", short: "TRA", city: "Perugia", uf: "PG", colors: ["#0077B6", "#90E0EF"], pattern: "h", rep: 49, cap: 10000, nickname: "i Lacustri", mascot: "Pato", stadium: "Stadio del Lago", rival: "ita-conero"},
  {id: "ita-conero", name: "US Conero", short: "CON", city: "Ancona", uf: "AN", colors: ["#EF476F", "#FFD166"], pattern: "sash", rep: 47, cap: 9500, nickname: "gli Scoglianti", mascot: "Golfinho", stadium: "Stadio del Passetto", rival: "ita-trasimeno"},
  {id: "ita-ionica", name: "US Ionica", short: "ION", city: "Taranto", uf: "TA", colors: ["#7FB7BE", "#1B1B3A"], pattern: "v", rep: 44, cap: 9000, nickname: "gli Spartani", mascot: "Mexilhão", stadium: "Stadio del Mar Piccolo", rival: "ita-messapia"},
];
