// Portugal: 32 clubes fictícios, apelidos em português europeu,
// checados para não coincidir com clubes reais conhecidos. Ordem = prestígio:
// os 16 primeiros começam na Primeira Liga, os 16 seguintes na Segunda Liga.
import type { ClubSeed } from "../types";

export const POR_CLUBS: ClubSeed[] = [
  // Primeira Liga
  {id: "por-invicta", name: "Invicta Futebol Clube", short: "INV", city: "Porto", uf: "POR", colors: ["#0E3B43", "#F2C14E"], pattern: "v", rep: 88, cap: 50000, nickname: "os Rabelos", mascot: "Lobo-ibérico", stadium: "Estádio da Ribeira", rival: "por-olisipo"},
  {id: "por-olisipo", name: "Sport Clube Olisipo", short: "OLI", city: "Lisboa", uf: "LIS", colors: ["#5B2A86", "#FFFFFF"], pattern: "h", rep: 87, cap: 52000, nickname: "os Galeões", mascot: "Corvo", stadium: "Estádio das Sete Colinas", rival: "por-tejo"},
  {id: "por-tejo", name: "Atlético Clube do Tejo", short: "TEJ", city: "Lisboa", uf: "LIS", colors: ["#12355B", "#F28C28"], pattern: "sash", rep: 84, cap: 44000, nickname: "os Navegadores", mascot: "Gaivota", stadium: "Estádio da Doca", rival: "por-olisipo"},
  {id: "por-bracara", name: "Bracara Futebol Clube", short: "BRA", city: "Braga", uf: "BRG", colors: ["#1F4E5F", "#E07A5F"], pattern: "v", rep: 80, cap: 30000, nickname: "os Legionários", mascot: "Águia-real", stadium: "Estádio da Colina Romana", rival: "por-afonsino"},
  {id: "por-afonsino", name: "Sport Clube Afonsino", short: "AFO", city: "Guimarães", uf: "BRG", colors: ["#B5121B", "#1E1E1E"], pattern: "h", rep: 78, cap: 29000, nickname: "os Fundadores", mascot: "Cavaleiro", stadium: "Estádio do Castelo", rival: "por-bracara"},
  {id: "por-mondego", name: "Académico do Mondego", short: "ACM", city: "Coimbra", uf: "CBR", colors: ["#1A1A2E", "#E2B714"], pattern: "sash", rep: 76, cap: 27000, nickname: "os Doutores", mascot: "Coruja", stadium: "Estádio do Choupal", rival: "por-uniaria"},
  {id: "por-uniaria", name: "União da Ria de Aveiro", short: "URA", city: "Aveiro", uf: "AVR", colors: ["#E4572E", "#FFFFFF"], pattern: "h", rep: 74, cap: 24000, nickname: "os Moliceiros", mascot: "Flamingo", stadium: "Estádio das Salinas", rival: "por-mondego"},
  {id: "por-zarco", name: "Clube Desportivo Zarco", short: "ZAR", city: "Funchal", uf: "MAD", colors: ["#006D77", "#FFD166"], pattern: "v", rep: 72, cap: 14000, nickname: "os Descobridores", mascot: "Lobo-marinho", stadium: "Estádio do Pico", rival: "por-laurissilva"},
  {id: "por-setecidades", name: "CD Sete Cidades", short: "SCI", city: "Ponta Delgada", uf: "AZO", colors: ["#2A9D8F", "#1D3557"], pattern: "half", rep: 70, cap: 12000, nickname: "os Vulcânicos", mascot: "Milhafre", stadium: "Estádio das Lagoas", rival: "por-heroismo"},
  {id: "por-ossonoba", name: "Ossonoba Futebol Clube", short: "OSS", city: "Faro", uf: "FAR", colors: ["#1D3557", "#F1FAEE"], pattern: "sash", rep: 68, cap: 18000, nickname: "as Cegonhas", mascot: "Cegonha", stadium: "Estádio da Ria", rival: "por-barlavento"},
  {id: "por-arrabida", name: "União da Arrábida", short: "ARR", city: "Setúbal", uf: "SET", colors: ["#6A4C93", "#FFCA3A"], pattern: "v", rep: 66, cap: 15000, nickname: "os Golfinhos", mascot: "Golfinho-roaz", stadium: "Estádio do Portinho", rival: "por-outrabanda"},
  {id: "por-pinhal", name: "GD Pinhal do Rei", short: "PIN", city: "Leiria", uf: "LEI", colors: ["#2D6A4F", "#D4A373"], pattern: "v", rep: 64, cap: 20000, nickname: "os Lenhadores", mascot: "Esquilo", stadium: "Estádio do Pinhal", rival: "por-templario"},
  {id: "por-serrapilar", name: "Serra do Pilar FC", short: "SPI", city: "Vila Nova de Gaia", uf: "POR", colors: ["#7B2D26", "#F2E8CF"], pattern: "h", rep: 63, cap: 12000, nickname: "os Tanoeiros", mascot: "Raposa", stadium: "Estádio das Caves", rival: "por-invicta"},
  {id: "por-outrabanda", name: "SC Outra Banda", short: "OBA", city: "Almada", uf: "SET", colors: ["#FF6B35", "#004E89"], pattern: "half", rep: 61, cap: 10000, nickname: "os Cacilheiros", mascot: "Garça", stadium: "Estádio da Margem Sul", rival: "por-arrabida"},
  {id: "por-ebora", name: "Grupo Desportivo Ebora", short: "EBO", city: "Évora", uf: "EVR", colors: ["#8C1C13", "#F4D35E"], pattern: "h", rep: 59, cap: 9000, nickname: "os Sobreiros", mascot: "Lince-ibérico", stadium: "Estádio da Muralha", rival: "por-planicie"},
  {id: "por-lanificios", name: "GD Lanifícios", short: "LAN", city: "Covilhã", uf: "CTB", colors: ["#4A4E69", "#F2E9E4"], pattern: "v", rep: 58, cap: 8000, nickname: "os Tecelões", mascot: "Carneiro", stadium: "Estádio dos Teares", rival: "por-egitania"},
  // Segunda Liga
  {id: "por-lima", name: "Atlético Clube do Lima", short: "LIM", city: "Viana do Castelo", uf: "VCT", colors: ["#0081A7", "#FDFCDC"], pattern: "h", rep: 64, cap: 9000, nickname: "os Garranos", mascot: "Garrano", stadium: "Estádio da Ponte Eiffel", rival: "por-bracara"},
  {id: "por-marao", name: "Sport Clube do Marão", short: "MAR", city: "Vila Real", uf: "VRL", colors: ["#344E41", "#DAD7CD"], pattern: "sash", rep: 62, cap: 7000, nickname: "os Serranos", mascot: "Lobo", stadium: "Estádio do Alvão", rival: "por-montesinho"},
  {id: "por-montesinho", name: "GD Montesinho", short: "MTS", city: "Bragança", uf: "BGC", colors: ["#9D0208", "#FFBA08"], pattern: "half", rep: 61, cap: 5000, nickname: "os Caretos", mascot: "Careto", stadium: "Estádio da Cidadela", rival: "por-marao"},
  {id: "por-barlavento", name: "Sport Clube Barlavento", short: "BAR", city: "Portimão", uf: "FAR", colors: ["#00B4D8", "#FFFFFF"], pattern: "v", rep: 59, cap: 8000, nickname: "os Marinheiros", mascot: "Sardinha", stadium: "Estádio da Praia", rival: "por-ossonoba"},
  {id: "por-templario", name: "Templário FC", short: "TEM", city: "Tomar", uf: "STR", colors: ["#FFFFFF", "#C1121F"], pattern: "sash", rep: 58, cap: 6000, nickname: "os Cavaleiros", mascot: "Cavaleiro templário", stadium: "Estádio do Convento", rival: "por-pinhal"},
  {id: "por-leziria", name: "Lezíria Futebol Clube", short: "LEZ", city: "Santarém", uf: "STR", colors: ["#606C38", "#FEFAE0"], pattern: "h", rep: 56, cap: 6500, nickname: "os Campinos", mascot: "Toiro", stadium: "Estádio das Portas do Sol", rival: "por-templario"},
  {id: "por-douro", name: "União do Douro", short: "DOU", city: "Peso da Régua", uf: "VRL", colors: ["#5E0B15", "#90A955"], pattern: "v", rep: 55, cap: 5500, nickname: "os Vinhateiros", mascot: "Melro", stadium: "Estádio dos Socalcos", rival: "por-marao"},
  {id: "por-laurissilva", name: "SC Laurissilva", short: "LAU", city: "Funchal", uf: "MAD", colors: ["#1B4332", "#FFFFFF"], pattern: "half", rep: 54, cap: 6000, nickname: "os Levadeiros", mascot: "Pombo-trocaz", stadium: "Estádio das Levadas", rival: "por-zarco"},
  {id: "por-heroismo", name: "GD Heroísmo", short: "HER", city: "Angra do Heroísmo", uf: "AZO", colors: ["#023E8A", "#FFD60A"], pattern: "h", rep: 52, cap: 5000, nickname: "os Bravos", mascot: "Toiro bravo", stadium: "Estádio do Monte Brasil", rival: "por-setecidades"},
  {id: "por-lafoes", name: "Sport Clube de Lafões", short: "LAF", city: "São Pedro do Sul", uf: "VIS", colors: ["#8338EC", "#FFFFFF"], pattern: "sash", rep: 51, cap: 4500, nickname: "os Termais", mascot: "Truta", stadium: "Estádio das Termas", rival: "por-mondego"},
  {id: "por-planicie", name: "Desportivo da Planície", short: "PLA", city: "Beja", uf: "BEJ", colors: ["#E9C46A", "#6B4226"], pattern: "h", rep: 50, cap: 4500, nickname: "os Ceifeiros", mascot: "Abetarda", stadium: "Estádio da Planície Dourada", rival: "por-ebora"},
  {id: "por-riaformosa", name: "Ria Formosa FC", short: "RFO", city: "Tavira", uf: "FAR", colors: ["#48CAE4", "#03045E"], pattern: "half", rep: 48, cap: 4000, nickname: "os Atuneiros", mascot: "Cavalo-marinho", stadium: "Estádio da Ponte Romana", rival: "por-ossonoba"},
  {id: "por-egitania", name: "Académico da Egitânia", short: "EGI", city: "Guarda", uf: "GRD", colors: ["#1B263B", "#E0E1DD"], pattern: "v", rep: 47, cap: 4000, nickname: "os Beirões", mascot: "Cão da Serra", stadium: "Estádio da Torre de Menagem", rival: "por-lanificios"},
  {id: "por-miragaia", name: "Sport Clube Miragaia", short: "MIR", city: "Porto", uf: "POR", colors: ["#3D405B", "#F2CC8F"], pattern: "h", rep: 46, cap: 3500, nickname: "os Ribeirinhos", mascot: "Corvo-marinho", stadium: "Estádio da Alfândega", rival: "por-invicta"},
  {id: "por-alfacinha", name: "Desportivo Alfacinha", short: "ALF", city: "Lisboa", uf: "LIS", colors: ["#52B788", "#081C15"], pattern: "v", rep: 45, cap: 3500, nickname: "os Bairristas", mascot: "Varina", stadium: "Estádio do Miradouro", rival: "por-tejo"},
  {id: "por-beirabaixa", name: "Beira Baixa FC", short: "BBX", city: "Castelo Branco", uf: "CTB", colors: ["#B08968", "#FFFFFF"], pattern: "sash", rep: 44, cap: 3000, nickname: "os Raianos", mascot: "Grifo", stadium: "Estádio do Cabeço", rival: "por-lanificios"},
];
